# Generated by Django 4.2 on 2023-05-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_slug_remove_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
