# Generated by Django 4.2 on 2023-05-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_us_booking_form_date_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_Form',
            new_name='BookingForm',
        ),
    ]
