# Generated by Django 4.2 on 2023-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gallery_imageslider_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='feedback',
            new_name='message',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('1 Star', '1 Star'), ('2 Star', '2 Star'), ('3 Star', '3 Star'), ('4 Star', '4 Star'), ('5 Star', '5 Star')], max_length=100),
        ),
    ]
