# Generated by Django 4.2 on 2023-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_review_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslider',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imageslider',
            name='slider_img',
            field=models.ImageField(blank=True, upload_to='media/slider-img'),
        ),
        migrations.AddField(
            model_name='imageslider',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100),
        ),
        migrations.AddField(
            model_name='imageslider',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
