# Generated by Django 4.2 on 2023-05-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactus_delete_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBookForm',
            new_name='TableBookForm',
        ),
    ]
