# Generated by Django 4.2 on 2023-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
