# Generated by Django 4.2 on 2023-05-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cart_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
