# Generated by Django 4.2 on 2023-05-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_cart_title_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.IntegerField(null=True),
        ),
    ]
