# Generated by Django 4.2 on 2023-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
