# Generated by Django 4.2 on 2023-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesNearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
