# Generated by Django 4.2 on 2023-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_placesnearby_gallery_date_field_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesnearby',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placesnearby',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/gallery'),
        ),
        migrations.AddField(
            model_name='placesnearby',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
