# Generated by Django 4.2 on 2023-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_cateringbook_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringbook',
            name='event_dates',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
