# Generated by Django 4.2 on 2023-06-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cateringbook_event_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringbook',
            name='event_dates',
        ),
    ]
