# Generated by Django 4.2 on 2023-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_cateringbook_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringbook',
            name='estimated_no_of_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cateringbook',
            name='event_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cateringbook',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cateringbook',
            name='event_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cateringbook',
            name='food_served',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cateringbook',
            name='time_of_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
