# Generated by Django 4.2 on 2023-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_cateringbook_estimated_no_of_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='estimated_no_of_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='event_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='event_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='food_served',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='time_of_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
